- CODE_OF_CONDUCT.md
> 📃 Code of conduct - added

- CONTRIBUTING.md
> 🤝 Contributing.md - added

- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
> 🐛 issue templates - added

- LICENSE
- README.md
> 😑 fix: update links and license

- .circleci/config.yml
> 🐛 fix: version

- src/data/contributors/harshilparmar.json
@iamdarshshah Added my profile data 👍
> Add Self introduction data file

- src/components/Header/Header.js
- src/components/Header/Header.styles.js
Turns the flex direction to column to look better on mobile devices
> feat: navbar mobile responsive

- src/contributors/vae97.json
created vae97.json file in src/contributors/  folder.
> My Details added

- src/contributors/Mayankjha997.json
- src/contributors/mayank_jha.json
> Mayankjha997.json

- src/contributors/yusufalp.json
Added a new participant named Yusuf Alp
> Added participant Yusuf Alp

- src/contributors/vineetnilawar.json
added vineetnilawar.json in contributers
> created vineetnilawar.json

- src/contributors/nataliepina.json
> Add myself to contributors

- src/contributors/beatrizsmerino.json
Added beatrizsmerino.json to the 'src/contributtors'
> Hacktoberfest Community - Add yourself to the list #21

- src/contributors/LeoAlvarenga.json
Hey! i'm a begginer coder participating the hacktoberfest, i hope you accept my contribution.
> Add new contributor

- src/contributors/mohammadanang.json
> Add me as contributors

- src/contributors/A7abhilash.json
Hacktoberfest Community - Add myself to the list #21 .
> Added new contributor

- src/contributors/sudiptog81.json
Added `sudiptog81.json` in `src/contributors`.
> adding sudiptog81

- src/contributors/RaviMengar.json
Adding as a new contributor...
> RaviMengar.json

- src/contributors/stanjdev.json
Starred the repo and added myself to the contributors list!
Thank you!
> Created stanjdev.json

- src/contributors/mohprilaksono.json
> add contributors

- src/contributors/savanipoojan78.json
> added contributor Poojan

- .prettierrc
- src/components/Content/Content.js
- src/components/Content/Content.styles.js
- src/components/Profile/Profile.js
- src/components/Profile/Profile.styles.js
- src/components/pullRequest/countPullRequest.js
- src/config/constants.js
- src/config/theme.js
Profile Modal that shows a list of PRs !
> 🎉feat: profile modal

- src/components/Content/Content.js
- src/components/Content/SearchTextField.js
> Added search functionality

- src/contributors/johnquintero.json
> New Contributor

- src/contributors/Mohit123singh.json
Please Add My Name to your contributor List.Thanks in Advance........
> Added My name to Contributor List

- src/contributors/FrejBjornsson.json
Added my info for #Hacktoberfest
#21
> Added my info (FrejBjornsson)

- src/contributors/luisrondow.json
Add myself to Contributor list (#21).
Thanks! :)
> Add luisrondow.json

- src/contributors/asadkhalid305.json
I have added asadkhalid305.json file to contributor folder.
> Added [name].json to contributor

- src/contributors/raneyash.json
Reverts iamdarshshah/hacktoberfest-participants#28
> Revert "Create raneyash.json"

- src/contributors/FrejBjornsson.json
> Fix Frej's file encoding

- src/contributors/amritanshusikdar.json
Added my contributor data in JSON file (amritanshusikdar.json)
> add amritanshusikdar.json

- src/contributors/johnisaig.json
Adding my selft in contributor thanks.
> Adding MySelf In Contributors

- package-lock.json
- package.json
- src/components/PRStatus/PRStatus.js
- src/components/Profile/Profile.js
- src/components/Profile/Profile.styles.js
- src/pages/index.js
Style user model PR list.
Add custom scroll bar.
> 137 change user model style

- src/contributors/ElizabethWoodhouse.json
Thank you for putting this hacktoberfest project together! It's great for beginners!
> Added my user information to project

- src/contributors/Ashyum.json
Added about myself in src/contributors folder.
> Ashyum.json

- src/contributors/stevenanthonyrevo.json
Hacktoberfest Participant Added to List
> Added Contributor to list

- src/contributors/headStyleColorRed.json
I added my name to this actually quite cool project
> Added my name :D

- src/contributors/RebaiAhmed.json
Adding myself to the Contributor list
> Added RebaiAhmed.json 
